const Menu = [
  {
    id: 1,
    image: "assets/images/book.png",
    imageFluid: "assets/images/bookFlud.png",
    name: "Kitob 1",
    category: "ilmiy adabiyotlar",
    price: "50.000",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    condition: "eski",
  },

  {
    id: 2,
    image: "assets/images/book.png",
    imageFluid: "assets/images/bookFlud.png",
    name: "Kitob 2",
    category: "chet el adabiyotlar",
    price: "120.000",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    condition: "yangi",
  },
  {
    id: 3,
    image: "assets/images/book.png",
    imageFluid: "assets/images/bookFlud.png",
    name: "Kitob 3",
    category: "adabiy kitoblar",
    price: "50.000",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    condition: "eski",
  },
  {
    id: 4,
    image: "assets/images/book.png",
    imageFluid: "assets/images/bookFlud.png",
    name: "Kitob 4",
    category: "adabiy kitoblar",
    price: "50.000",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    condition: "yangi",
  },
  {
    id: 5,
    image: "assets/images/book.png",
    imageFluid: "assets/images/bookFlud.png",
    name: "Kitob 5",
    category: "ilmiy adabiyotlar",
    price: "80.000",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    condition: "eski",
    discount: "10%",
  },
  {
    id: 6,
    image: "assets/images/book.png",
    imageFluid: "assets/images/bookFlud.png",
    name: "Kitob 6",
    category: "chet el adabiyotlar",
    price: "180.000",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    condition: "eski",
  },
  {
    id: 7,
    image: "assets/images/book.png",
    imageFluid: "assets/images/bookFlud.png",
    name: "Kitob 7",
    category: "ilmiy adabiyotlar",
    price: "60.000",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    discount: "10%",
    condition: "yangi",
  },
  {
    id: 8,
    image: "assets/images/book.png",
    imageFluid: "assets/images/bookFlud.png",
    name: "Kitob 8",
    category: "fantastik asarlar",
    price: "60.000",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    condition: "yangi",
  },
  {
    id: 9,
    image: "assets/images/book.png",
    imageFluid: "assets/images/bookFlud.png",
    name: "Kitob 9",
    category: "ilmiy adabiyotlar",
    price: "10.000",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    condition: "eski",
  },
];

export default Menu;
